### PR TITLE
throw away lombok and add compression handlers if needed

### PR DESCRIPTION
**Pull request by creeper123123321**

### CODE REVIEW

**Comment by creeper123123321** [comment]
TODO: check if it did break server compression handling

**Comment by creeper123123321** [comment]
it did break

**Comment by creeper123123321** [comment]
Fixed.

**Comment by KennyTV** [comment]
Need to replace spaces with tabs again 👀

**Comment by creeper123123321** [comment]
Velocity 1.1.0 was released. This PR fixes some issues when using a 1.7 client.

**Pull request closed without merging**
