### PR TITLE
Delaying PacketPlayInArmAnimation for 1.8->1.9 properly

### PR DESCRIPTION
**Pull request by funkemunky**
Fully explained in the comments, but PacketPlayInArmAnimation would be sent after PacketPlayInFlying, causing false positives on anticheats. This way, they will still always be sent after PacketPlayInUseEntity but before PacketPlayInFlying.

### CODE REVIEW

**Comment by funkemunky** [comment]
I fixed conflicts for this branch. Hopefully this can be merged into master now

**Comment by xkeksi** [comment]
hmmmmm when

**Comment by funkemunky** [comment]
@Gerrygames hey when will this be put into ViaRewind? My customers who use ViaRewind are having issues with the release builds and have to keep sending them my modified versionb.

**Comment by 7Sence** [comment]
When will this be merged, it's quite important to stop false bans

**Comment by Kichura** [comment]
> When will this be merged, it's quite important to stop false bans

There is no ETA for when pull requests will be merged / checked out properly as this usually boils down to lack of time or because different things are currently planned for via* functionality at the moment.

**Comment by funkemunky** [comment]
@Kichura okay. I mean this bit of code has been fairly well tested at this point considering the amount of servers just using a patched version with this bit of code instead of the one distributed officially. 

Would be good to be implemented before this becomes a year old...

**Comment by MWHunter** [comment]
Able to confirm the issue, a 1.8 player on a 1.18 server gets kicked when building due to this change: https://www.youtube.com/watch?v=OT7SGsFOCkY

**Comment by MachineBreaker** [comment]
Any possibility to merge this? I tested this on a 100 on server without issues

**Comment by LIWKK** [comment]
@kennytv

**Comment by MWHunter** [comment]
This is still actively causing falses on grim when clicking over 20 CPS.  Please merge this.

**Comment by FlorianMichael** [comment]
LGTM!

**Pull request merged**
